package ir.maxv.securevault

import ir.maxv.securevault.core.OtpCode
import ir.maxv.securevault.core.Totp
import ir.maxv.securevault.core.TotpSpec
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File
import java.net.URI

/**
 * The one-time-code reader: the RFC 6238 vectors, the three stored shapes, and a row-for-row
 * comparison against the desktop implementation's own output (`tools/make_totp_fixture.py`).
 *
 * The fixture is the part that matters most: it is generated by `vault.core.totp` — the code the
 * desktop viewer and the browser add-on already run — so these tests fail if this client ever
 * drifts from the codes the rest of the vault shows for the same entry.
 */
class TotpTest {

    private val fixture: JSONObject by lazy {
        val url = TotpTest::class.java.getResource("/fixture/totp_vectors.json")
            ?: error("fixture missing — run tools/make_totp_fixture.py")
        JSONObject(File(URI(url.toString())).readText(Charsets.UTF_8))
    }

    private val sha1Seed = "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ"
    private val sha256Seed = "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQGEZA"
    private val sha512Seed = "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ" +
        "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQGEZDGNA"

    @Test
    fun `RFC 6238 vectors for SHA-1`() {
        val spec = TotpSpec(secret = sha1Seed, digits = 8)
        val vectors = mapOf(
            59L to "94287082",
            1111111109L to "07081804",
            1111111111L to "14050471",
            1234567890L to "89005924",
            2000000000L to "69279037",
            20000000000L to "65353130",
        )
        for ((at, expected) in vectors) {
            assertEquals("T=$at", expected, Totp.codeFor(spec, at).first)
        }
    }

    @Test
    fun `RFC 6238 vectors for SHA-256 and SHA-512`() {
        val sha256 = TotpSpec(secret = sha256Seed, algorithm = "SHA256", digits = 8)
        val sha512 = TotpSpec(secret = sha512Seed, algorithm = "SHA512", digits = 8)
        assertEquals("46119246", Totp.codeFor(sha256, 59).first)
        assertEquals("90693936", Totp.codeFor(sha512, 59).first)
        assertEquals("68084774", Totp.codeFor(sha256, 1111111109).first)
        assertEquals("25091201", Totp.codeFor(sha512, 1111111109).first)
        assertEquals("67062674", Totp.codeFor(sha256, 1111111111).first)
        assertEquals("99943326", Totp.codeFor(sha512, 1111111111).first)
        assertEquals("91819424", Totp.codeFor(sha256, 1234567890).first)
        assertEquals("93441116", Totp.codeFor(sha512, 1234567890).first)
        assertEquals("90698825", Totp.codeFor(sha256, 2000000000).first)
        assertEquals("38618901", Totp.codeFor(sha512, 2000000000).first)
        assertEquals("77737706", Totp.codeFor(sha256, 20000000000).first)
        assertEquals("47863826", Totp.codeFor(sha512, 20000000000).first)
    }

    @Test
    fun `base32 decoding tolerates padding and spaces, and refuses anything else`() {
        assertEquals("12345678901234567890", Totp.base32Decode(sha1Seed)!!.toString(Charsets.ISO_8859_1))
        assertEquals(
            "12345678901234567890",
            Totp.base32Decode("gezd gnbvgy3tqojq gezd gnbvgy3tqojq====")!!.toString(Charsets.ISO_8859_1),
        )
        assertNull("a character outside the alphabet is not a seed", Totp.base32Decode("0189!"))
        assertNull("an empty seed is nothing", Totp.base32Decode(""))
    }

    @Test
    fun `a seed must look like one, so prose is never turned into a code`() {
        assertTrue(Totp.looksLikeSecret("JBSWY3DPEHPK3PXP"))
        assertTrue(!Totp.looksLikeSecret("RECOVERY CODES HERE"))
        assertTrue(!Totp.looksLikeSecret("ABCDEF"))
    }

    @Test
    fun `an otpauth URI carries its parameters, with the RFC defaults when it does not`() {
        val parsed = Totp.parseOtpauth(
            "otpauth://totp/GitHub:max%40example.com?secret=JBSWY3DPEHPK3PXP" +
                "&issuer=GitHub&digits=8&period=60&algorithm=SHA256",
        )!!
        assertEquals("JBSWY3DPEHPK3PXP", parsed.secret)
        assertEquals("GitHub", parsed.issuer)
        assertEquals("GitHub:max@example.com", parsed.label)
        assertEquals(8, parsed.digits)
        assertEquals(60, parsed.period)
        assertEquals("SHA256", parsed.algorithm)

        val plain = Totp.parseOtpauth("otpauth://totp/x?secret=$sha1Seed")!!
        assertEquals(6, plain.digits)
        assertEquals(30, plain.period)
        assertEquals("SHA1", plain.algorithm)
        assertEquals("the label is the URI's path after the type", "x", plain.label)

        assertNull("hotp needs a counter we do not store", Totp.parseOtpauth("otpauth://hotp/x?secret=AA"))
        assertNull("a bare seed is not a URI", Totp.parseOtpauth(sha1Seed))
    }

    @Test
    fun `out-of-range parameters are clamped, never fatal`() {
        val tiny = Totp.parseOtpauth("otpauth://totp/x?secret=$sha1Seed&digits=3&period=1")!!
        assertEquals(Totp.MIN_DIGITS, tiny.digits)
        assertEquals(Totp.MIN_PERIOD, tiny.period)
        val huge = Totp.parseOtpauth("otpauth://totp/x?secret=$sha1Seed&digits=12")!!
        assertEquals(Totp.MAX_DIGITS, huge.digits)
        val unknown = Totp.parseOtpauth("otpauth://totp/x?secret=$sha1Seed&algorithm=SHA999")!!
        assertEquals(Totp.DEFAULT_ALGORITHM, unknown.algorithm)
    }

    @Test
    fun `the three stored shapes and what must not be a code`() {
        val uri = Totp.valueToCode("otpauth://totp/x?secret=$sha1Seed", 59)!!
        assertTrue(uri.live)
        assertEquals("287082", uri.code)
        assertEquals(1, uri.remaining)

        val bare = Totp.valueToCode(sha1Seed, 59)!!
        assertTrue(bare.live)
        assertEquals("287082", bare.code)

        val pasted = Totp.valueToCode("654321", 59)!!
        assertEquals("654321", pasted.code)
        assertTrue("a pasted code does not rotate", !pasted.live)
        assertEquals("static", pasted.kind)
        assertNull("a static code has no countdown", pasted.remaining)

        assertNull("the migration's empty marker is not a code", Totp.valueToCode("—", 59))
        assertNull("prose is not a code", Totp.valueToCode("recovery codes below", 59))
        assertNull("hotp is not supported", Totp.valueToCode("otpauth://hotp/x?secret=$sha1Seed", 59))
    }

    @Test
    fun `grouping is presentation only, and the value to copy never has a space`() {
        val grouped = OtpCode("287082", live = true, remaining = 1, period = 30, digits = 6)
        assertEquals("287 082", grouped.display)
        assertEquals("287082", grouped.code)

        // the desktop rule: n % 3 == 0 → triplets, else an even length → halves
        assertEquals("123 456 789", OtpCode("123456789", true, 1, 30, 9).display)
        assertEquals("9428 7082", OtpCode("94287082", true, 1, 30, 8).display)
        assertEquals("12345 67890", OtpCode("1234567890", true, 1, 30, 10).display)
        assertEquals("12345", OtpCode("12345", true, 1, 30, 5).display)

        // a backup code is typed exactly as stored
        assertEquals("1234567890", OtpCode("1234567890", false, null, 30, 10).display)
        assertEquals("654321", OtpCode("654321", false, null, 30, 6).display)
    }

    @Test
    fun `every row of the desktop fixture agrees, code for code`() {
        val rows = fixture.getJSONArray("codes")
        var readable = 0
        for (index in 0 until rows.length()) {
            val row = rows.getJSONObject(index)
            val value = row.getString("value")
            val at = row.getLong("at")
            val expected = if (row.isNull("code")) null else row.getString("code")
            val code = Totp.valueToCode(value, at)
            if (expected == null) {
                assertNull("`$value` must not yield a code", code)
                continue
            }
            readable += 1
            assertNotNull("`$value` must yield a code", code)
            assertEquals("code of `$value` at $at", expected, code!!.code)
            assertEquals("display of `$value`", row.getString("display"), code.display)
            assertEquals("live of `$value`", row.getBoolean("live"), code.live)
            assertEquals("kind of `$value`", row.getString("kind"), code.kind)
            if (!row.isNull("period")) assertEquals("period of `$value`", row.getInt("period"), code.period)
            if (!row.isNull("digits")) assertEquals("digits of `$value`", row.getInt("digits"), code.digits)
            if (!row.isNull("remaining")) assertEquals("remaining of `$value`", row.getInt("remaining"), code.remaining)
            if (!row.isNull("algorithm")) assertEquals("algorithm of `$value`", row.getString("algorithm"), code.algorithm)
            if (!row.isNull("issuer")) assertEquals("issuer of `$value`", row.getString("issuer"), code.issuer)
            if (!row.isNull("label")) assertEquals("label of `$value`", row.getString("label"), code.label)
        }
        assertTrue("the fixture must contain live rows to be worth anything", readable >= 10)
    }
}
